### ISSUE TITLE
mesh extraction

### ISSUE THREAD

**Issue by tuning12** [baaivision/GeoDream#8]
First thank you for your great work!

I didn't quite understand what the "parsed.yaml" means in mesh extraction. Could you please specify it?

**Comment by mabaorui** [comment]
Hi,
Thank you for your attention.
After following the instructions in this section (https://github.com/baaivision/GeoDream#geodream-training) and executing Stage 3 (DMTet Texturing), a parsed.yaml file will be automatically generated in the output folder. This yaml file records the configuration of the current running program. Once Stage 3 is completed, you can assign the '--config' parameter the value of the yaml file generated in Stage 3 for mesh extraction.

**Comment by tuning12** [comment]
Thank you for your reply. Is there any pretrained model provided? I have read the README.md but not found the url of the pretrained model.

**Comment by mabaorui** [comment]
Hi,
The pretrained model is still being organized, and we will release it as soon as possible. We hope you can continue to follow our updates. Meanwhile, we also recommend that you follow the GitHub instructions to generate your own 3D model by providing your prompt and reference images.

I am closing this issue. If you have any more questions, please feel free to reopen it or create new issues.
If you find GeoDream helpful, please consider star this repository. Thanks~ :)
